Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -11,24 +11,24 @@ on:
 jobs:
   security:
     runs-on: ubuntu-latest
+    env: 
+      RESULTS_FILE: "./results.json"
     steps:    
       - uses: actions/checkout@master
       - name: Run Snyk to check for vulnerabilities
         uses: snyk/actions/maven@master
-        # continue-on-error: true #${{ vars.CONTINUE == 'true' }}
+        continue-on-error: true #${{ vars.CONTINUE == 'true' }}
         env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           command: code test
-          args: "--json-file-output=./results.json --org=${{ vars.ORG_ID }} --project-name=${{ vars.PROJECT_NAME }} --severity-threshold=${{ vars.SEVERITY_THRESHOLD }}"
+          args: "--json-file-output=${{ RESULTS_FILE }} --org=${{ vars.ORG_ID }} --project-name=${{ vars.PROJECT_NAME }} --severity-threshold=${{ vars.SEVERITY_THRESHOLD }}"
       - if: ${{ always() }}
-        run: |
-          echo "RESULTS_PRESENT=$(echo $(if [[ -f "results.json" ]]; then echo 'true'; else echo 'false'; fi))" >> "$GITHUB_ENV"
+        run: echo "RESULTS_PRESENT=$(echo $(if [[ -f "${{ RESULTS_FILE }}" ]]; then echo 'true'; else echo 'false'; fi))" >> "$GITHUB_ENV"
       - name: Check if any of the priority scores are above set threshold  
         if: ${{ always() }} ${{ env.RESULTS_PRESENT == 'true' }} 
         # continue-on-error: false
-        run: |
-          "cat ./results.json | jq -e 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo '::error::Priority Score exceeded';exit 1"
+        run: "cat ${{ RESULTS_FILE }} | jq -e 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo '::error::Priority Score exceeded';exit 1"
         shell: bash
 
 
