Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -22,11 +22,11 @@ jobs:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
         with:
           command: code test
-          args: "--json-file-output=${RESULTS_FILE} --org=${{ vars.ORG_ID }} --project-name=${{ vars.PROJECT_NAME }} --severity-threshold=${{ vars.SEVERITY_THRESHOLD }}"
+          args: "--json-file-output=${{ env.RESULTS_FILE }} --org=${{ vars.ORG_ID }} --project-name=${{ vars.PROJECT_NAME }} --severity-threshold=${{ vars.SEVERITY_THRESHOLD }}"
       - name: Check if any of the priority scores are above set threshold  
         run: |
-          echo "RESULTS_PRESENT=$(echo $(if [[ -f ${RESULTS_FILE} ]]; then echo 'true'; else echo 'false'; fi))" >> "$GITHUB_ENV"
-          cat $RESULTS_FILE | jq -e 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo '::error::Priority Score exceeded'
+          echo "RESULTS_PRESENT=$(echo $(if [[ -f ${{ env.RESULTS_FILE }} ]]; then echo 'true'; else echo 'false'; fi))" >> "$GITHUB_ENV"
+          cat ${{ env.RESULTS_FILE} | jq -e 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo '::error::Priority Score exceeded'
         shell: bash
 
 
