Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -24,10 +24,10 @@ jobs:
           command: code test
           args: ${{ env.SNYK_ARGS }}
       - name: Test Priority Level
-        if: ${{ success() }}
+        if: $( `[[ -r "results.json" ]]` )  #${{ success() }}
         # fail the scan if any priorty score is above our thereshold
         continue-on-error: false
-        run: "cat ./results.json | jq -e 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo '::error::Priority Score exceeded'"
+        run: "cat ./results.json | jq -e 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo '::error::Priority Score exceeded';exit 1"
         shell: bash
 
 
