Update snyk-security.yml

diff --git a/.github/workflows/snyk-security.yml b/.github/workflows/snyk-security.yml
--- a/.github/workflows/snyk-security.yml
+++ b/.github/workflows/snyk-security.yml
@@ -26,7 +26,7 @@ jobs:
       - name: Check if any of the priority scores are above set threshold  
         run: |
           echo "RESULTS_PRESENT=$(echo $(if [[ -f ${{ env.RESULTS_FILE }} ]]; then echo 'true'; else echo 'false'; fi))" >> "$GITHUB_ENV"
-          cat ${{ env.RESULTS_FILE} | jq -e 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo '::error::Priority Score exceeded'
+          cat ${{ env.RESULTS_FILE }} | jq -e 'any(.runs[].results[].properties.priorityScore; . >= ${{ vars.PRIORITY_SCORE }}) | not' >/dev/null || echo '::error::Priority Score exceeded'
         shell: bash
 
 
